// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scanorganizer} from '../models';

export function Append(arg1:string):Promise<void>;

export function GetInputFiles():Promise<Array<string>>;

export function GetOutputFoldersRecursive():Promise<Array<string>>;

export function GetPreview():Promise<scanorganizer.PreviewData>;

export function Rename(arg1:string,arg2:string):Promise<void>;

export function Trash():Promise<void>;
