// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Append(arg1) {
  return window['go']['main']['App']['Append'](arg1);
}

export function GetInputFiles() {
  return window['go']['main']['App']['GetInputFiles']();
}

export function GetOutputFoldersRecursive() {
  return window['go']['main']['App']['GetOutputFoldersRecursive']();
}

export function GetPreview() {
  return window['go']['main']['App']['GetPreview']();
}

export function Rename(arg1, arg2) {
  return window['go']['main']['App']['Rename'](arg1, arg2);
}

export function Trash() {
  return window['go']['main']['App']['Trash']();
}
