// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scanorganizer$0 from "./internal/scanorganizer/models.js";

/**
 * @param {string[]} paths
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function AddFiles(paths, mode) {
    return $Call.ByID(2632649643, paths, mode);
}

/**
 * @param {string} target
 * @returns {$CancellablePromise<void>}
 */
export function Append(target) {
    return $Call.ByID(1572826137, target);
}

/**
 * @param {string} destination
 * @returns {$CancellablePromise<void>}
 */
export function Export(destination) {
    return $Call.ByID(1718700699, destination);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetInputFiles() {
    return $Call.ByID(1806227512).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetOutputFiles() {
    return $Call.ByID(1470086069).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetOutputFoldersRecursive() {
    return $Call.ByID(3274735821).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<scanorganizer$0.PreviewData | null>}
 */
export function GetPreview() {
    return $Call.ByID(106795641).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<scanorganizer$0.StatusData | null>}
 */
export function GetStatus() {
    return $Call.ByID(1043986649).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} newName
 * @param {string} folder
 * @returns {$CancellablePromise<void>}
 */
export function Rename(newName, folder) {
    return $Call.ByID(3432540379, newName, folder);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function SelectExportDirectory() {
    return $Call.ByID(3958356690);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Trash() {
    return $Call.ByID(1787639213);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = scanorganizer$0.PreviewData.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = scanorganizer$0.StatusData.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
