// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class PreviewData {
    /**
     * Creates a new PreviewData instance.
     * @param {Partial<PreviewData>} [$$source = {}] - The source object to create the PreviewData.
     */
    constructor($$source = {}) {
        if (!("preview" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["preview"] = "";
        }
        if (!("previousRenamed" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["previousRenamed"] = [];
        }
        if (!("folders" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["folders"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PreviewData}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("previousRenamed" in $$parsedSource) {
            $$parsedSource["previousRenamed"] = $$createField1_0($$parsedSource["previousRenamed"]);
        }
        if ("folders" in $$parsedSource) {
            $$parsedSource["folders"] = $$createField2_0($$parsedSource["folders"]);
        }
        return new PreviewData(/** @type {Partial<PreviewData>} */($$parsedSource));
    }
}

export class StatusData {
    /**
     * Creates a new StatusData instance.
     * @param {Partial<StatusData>} [$$source = {}] - The source object to create the StatusData.
     */
    constructor($$source = {}) {
        if (!("inputCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["inputCount"] = 0;
        }
        if (!("outputCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["outputCount"] = 0;
        }
        if (!("isFullyProcessed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isFullyProcessed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StatusData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusData(/** @type {Partial<StatusData>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
